# Generated by Django 5.2.9 on 2025-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название устройства')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('status', models.CharField(choices=[('on', 'Включено'), ('off', 'Выключено'), ('unknown', 'Неизвестно'), ('offline', 'Не в сети')], default='unknown', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['name'],
            },
        ),
    ]
